### PR TITLE
fix : Ensure scraper does not fetch bot events

### PR DESCRIPTION
**Pull request by dharmik3504**
Proposed Changes

Fix: #554

Description 

i have just filter out the [bot] slug file name while picking it  in first rendering . 

Reviewer(s)

@rithviknishad

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
although this solves the side effect, this does not solve the root cause. we shouldn't be storing events of bots in the first place.

**Comment by dharmik3504** [comment]
> although this solves the side effect, this does not solve the root cause. we shouldn't be storing events of bots in the first place.

do you want me to check that scenario as well ??  or you are opening a new issue for that ??

**Comment by rithviknishad** [comment]
nope it's the same issue. and only check for that scenario.

data repo migration to remove bot's data will be handled separately.

**Comment by dharmik3504** [comment]
hello @rithviknishad 
is there a way to run the project locally without  data-repo  data ?

**Comment by rithviknishad** [comment]
nope. just run `pnpm load-data` to load data from data-repo

**Comment by dharmik3504** [comment]
so the data will be pick from data-repo only (the MD file ) and i want hit any event so how i can re-produce the issue as while debugging it redirect me to same function (getContributorsSlugs) which is inside lib/api.ts .

**Comment by rithviknishad** [comment]
#554 has been fixed btw:

https://github.com/ohcnetwork/leaderboard/compare/a253e309a244ee4342639182755555f90763874e...a3b377b91de86335ca457087399eef6b693873ff

**Pull request closed without merging**
