### PR TITLE
Fix:  fetch events for bots

### PR DESCRIPTION
**Pull request by AdityaJ2305**
# Proposed Changes
Fix: #554 

# Reviewer(s)
@rithviknishad

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
If this change prevented the issue, the previous change also prevented the issue... Are you sure this is right?

image

**Comment by AdityaJ2305** [comment]
> If this change prevented the issue, the previous change also prevented the issue... Are you sure this is right?
> 
> image

Let me check 😅

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad, I don’t think this issue is coming from this piece of [code](https://github.com/ohcnetwork/leaderboard/blob/21a7beb26d93fd71f38d8ed7b78d86e5031d9296/scraper/src/github-scraper/fetchEvents.ts#L30-L32). There seems to be something else causing it.

**Comment by rithviknishad** [comment]
Looking at this: https://flatgithub.com/ohcnetwork/leaderboard-data?filename=data%2Fgithub%2Fdependabot%5Bbot%5D.json&sha=98a8603b63dd721a726a2e52c14014067c7e1f0e&tab=activity

Looks like only PR Merged events are there. And I had merged dependabot's PRs that day. So likely some incorrect logic there?

**Comment by AdityaJ2305** [comment]
> Looking at this: https://flatgithub.com/ohcnetwork/leaderboard-data?filename=data%2Fgithub%2Fdependabot%5Bbot%5D.json&sha=98a8603b63dd721a726a2e52c14014067c7e1f0e&tab=activity
> 
> Looks like only PR Merged events are there. And I had merged dependabot's PRs that day. So even though I was the one who merged it, the author of the PR is still dependabot. So likely some incorrect logic there maybe?
> 
> The Author of the PR should get the event and not the one who merged it.
> 
> https://github.com/ohcnetwork/leaderboard/blob/be46e0b5dd8d35493f4ea59f752ea2240a03ddcb/scraper/src/github-scraper/parseEvents.ts#L204-L211

Let me check

**Comment by AdityaJ2305** [comment]
> > Looking at this: https://flatgithub.com/ohcnetwork/leaderboard-data?filename=data%2Fgithub%2Fdependabot%5Bbot%5D.json&sha=98a8603b63dd721a726a2e52c14014067c7e1f0e&tab=activity
> > Looks like only PR Merged events are there. And I had merged dependabot's PRs that day. So even though I was the one who merged it, the author of the PR is still dependabot. So likely some incorrect logic there maybe?
> > The Author of the PR should get the event and not the one who merged it.
> > https://github.com/ohcnetwork/leaderboard/blob/be46e0b5dd8d35493f4ea59f752ea2240a03ddcb/scraper/src/github-scraper/parseEvents.ts#L204-L211
> 
> Let me check
> 
> @rithviknishad, Am I understanding it wrong? It is okay na if the author is dependabot for its PRs. The error is why it is not getting ignore due to this line 👇
> 
> https://github.com/ohcnetwork/leaderboard/blob/be46e0b5dd8d35493f4ea59f752ea2240a03ddcb/scraper/src/github-scraper/parseEvents.ts#L150

@rithviknishad

**Comment by rithviknishad** [comment]
inactive

**Pull request closed without merging**
