### PR TITLE
Add logo.png to repository 

### PR DESCRIPTION
**Pull request by DonXavierdev**

### CODE REVIEW

**Comment by DonXavierdev** [comment]
@rithviknishad i think this will solve the issue .

**Comment by DonXavierdev** [comment]
Fixes #588

**Comment by rithviknishad** [comment]
Late for review, but we are not supposed to git track org. specific things in this repo. Use leaderboard-data repo for OHC org. specific configurations.

**Comment by DonXavierdev** [comment]
@rithviknishad ok i will gitignore logo.png in leaderboard and create api to fetch it from leaderboard-data is it a valid approach ?

**Pull request merged**
